// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: proto/cloudboard/jobauth/jobauth.proto

package jobauth

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	JobAuth_GenerateToken_FullMethodName = "/cloudboard.jobauth.JobAuth/GenerateToken"
	JobAuth_ValidateToken_FullMethodName = "/cloudboard.jobauth.JobAuth/ValidateToken"
)

// JobAuthClient is the client API for JobAuth service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// JobAuth service issues and validates per-job tokens.
type JobAuthClient interface {
	// GenerateToken issues a new token for a job.
	GenerateToken(ctx context.Context, in *GenerateTokenRequest, opts ...grpc.CallOption) (*GenerateTokenResponse, error)
	// ValidateToken checks if a token is valid.
	ValidateToken(ctx context.Context, in *ValidateTokenRequest, opts ...grpc.CallOption) (*ValidateTokenResponse, error)
}

type jobAuthClient struct {
	cc grpc.ClientConnInterface
}

func NewJobAuthClient(cc grpc.ClientConnInterface) JobAuthClient {
	return &jobAuthClient{cc}
}

func (c *jobAuthClient) GenerateToken(ctx context.Context, in *GenerateTokenRequest, opts ...grpc.CallOption) (*GenerateTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateTokenResponse)
	err := c.cc.Invoke(ctx, JobAuth_GenerateToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobAuthClient) ValidateToken(ctx context.Context, in *ValidateTokenRequest, opts ...grpc.CallOption) (*ValidateTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateTokenResponse)
	err := c.cc.Invoke(ctx, JobAuth_ValidateToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JobAuthServer is the server API for JobAuth service.
// All implementations must embed UnimplementedJobAuthServer
// for forward compatibility.
//
// JobAuth service issues and validates per-job tokens.
type JobAuthServer interface {
	// GenerateToken issues a new token for a job.
	GenerateToken(context.Context, *GenerateTokenRequest) (*GenerateTokenResponse, error)
	// ValidateToken checks if a token is valid.
	ValidateToken(context.Context, *ValidateTokenRequest) (*ValidateTokenResponse, error)
	mustEmbedUnimplementedJobAuthServer()
}

// UnimplementedJobAuthServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedJobAuthServer struct{}

func (UnimplementedJobAuthServer) GenerateToken(context.Context, *GenerateTokenRequest) (*GenerateTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateToken not implemented")
}
func (UnimplementedJobAuthServer) ValidateToken(context.Context, *ValidateTokenRequest) (*ValidateTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateToken not implemented")
}
func (UnimplementedJobAuthServer) mustEmbedUnimplementedJobAuthServer() {}
func (UnimplementedJobAuthServer) testEmbeddedByValue()                 {}

// UnsafeJobAuthServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JobAuthServer will
// result in compilation errors.
type UnsafeJobAuthServer interface {
	mustEmbedUnimplementedJobAuthServer()
}

func RegisterJobAuthServer(s grpc.ServiceRegistrar, srv JobAuthServer) {
	// If the following call pancis, it indicates UnimplementedJobAuthServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&JobAuth_ServiceDesc, srv)
}

func _JobAuth_GenerateToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobAuthServer).GenerateToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobAuth_GenerateToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobAuthServer).GenerateToken(ctx, req.(*GenerateTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobAuth_ValidateToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobAuthServer).ValidateToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobAuth_ValidateToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobAuthServer).ValidateToken(ctx, req.(*ValidateTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// JobAuth_ServiceDesc is the grpc.ServiceDesc for JobAuth service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var JobAuth_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cloudboard.jobauth.JobAuth",
	HandlerType: (*JobAuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateToken",
			Handler:    _JobAuth_GenerateToken_Handler,
		},
		{
			MethodName: "ValidateToken",
			Handler:    _JobAuth_ValidateToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/cloudboard/jobauth/jobauth.proto",
}
