// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/cloudboard/jobauth/jobauth.proto

package jobauth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenerateTokenRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Serialized job metadata (e.g., job ID, permissions).
	JobMetadata   []byte `protobuf:"bytes,1,opt,name=job_metadata,json=jobMetadata,proto3" json:"job_metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateTokenRequest) Reset() {
	*x = GenerateTokenRequest{}
	mi := &file_proto_cloudboard_jobauth_jobauth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateTokenRequest) ProtoMessage() {}

func (x *GenerateTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cloudboard_jobauth_jobauth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateTokenRequest.ProtoReflect.Descriptor instead.
func (*GenerateTokenRequest) Descriptor() ([]byte, []int) {
	return file_proto_cloudboard_jobauth_jobauth_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateTokenRequest) GetJobMetadata() []byte {
	if x != nil {
		return x.JobMetadata
	}
	return nil
}

type GenerateTokenResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Signed token blob.
	Token         []byte `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateTokenResponse) Reset() {
	*x = GenerateTokenResponse{}
	mi := &file_proto_cloudboard_jobauth_jobauth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateTokenResponse) ProtoMessage() {}

func (x *GenerateTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cloudboard_jobauth_jobauth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateTokenResponse.ProtoReflect.Descriptor instead.
func (*GenerateTokenResponse) Descriptor() ([]byte, []int) {
	return file_proto_cloudboard_jobauth_jobauth_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateTokenResponse) GetToken() []byte {
	if x != nil {
		return x.Token
	}
	return nil
}

type ValidateTokenRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Token to validate.
	Token         []byte `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenRequest) Reset() {
	*x = ValidateTokenRequest{}
	mi := &file_proto_cloudboard_jobauth_jobauth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenRequest) ProtoMessage() {}

func (x *ValidateTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cloudboard_jobauth_jobauth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenRequest.ProtoReflect.Descriptor instead.
func (*ValidateTokenRequest) Descriptor() ([]byte, []int) {
	return file_proto_cloudboard_jobauth_jobauth_proto_rawDescGZIP(), []int{2}
}

func (x *ValidateTokenRequest) GetToken() []byte {
	if x != nil {
		return x.Token
	}
	return nil
}

type ValidateTokenResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True if the token is valid.
	Valid         bool `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenResponse) Reset() {
	*x = ValidateTokenResponse{}
	mi := &file_proto_cloudboard_jobauth_jobauth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenResponse) ProtoMessage() {}

func (x *ValidateTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cloudboard_jobauth_jobauth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenResponse.ProtoReflect.Descriptor instead.
func (*ValidateTokenResponse) Descriptor() ([]byte, []int) {
	return file_proto_cloudboard_jobauth_jobauth_proto_rawDescGZIP(), []int{3}
}

func (x *ValidateTokenResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

var File_proto_cloudboard_jobauth_jobauth_proto protoreflect.FileDescriptor

const file_proto_cloudboard_jobauth_jobauth_proto_rawDesc = "" +
	"\n" +
	"&proto/cloudboard/jobauth/jobauth.proto\x12\x12cloudboard.jobauth\"9\n" +
	"\x14GenerateTokenRequest\x12!\n" +
	"\fjob_metadata\x18\x01 \x01(\fR\vjobMetadata\"-\n" +
	"\x15GenerateTokenResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\fR\x05token\",\n" +
	"\x14ValidateTokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\fR\x05token\"-\n" +
	"\x15ValidateTokenResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid2\xd5\x01\n" +
	"\aJobAuth\x12d\n" +
	"\rGenerateToken\x12(.cloudboard.jobauth.GenerateTokenRequest\x1a).cloudboard.jobauth.GenerateTokenResponse\x12d\n" +
	"\rValidateToken\x12(.cloudboard.jobauth.ValidateTokenRequest\x1a).cloudboard.jobauth.ValidateTokenResponseBCZAgithub.com/iamsourabh-in/security-pcc-go/proto/cloudboard/jobauthb\x06proto3"

var (
	file_proto_cloudboard_jobauth_jobauth_proto_rawDescOnce sync.Once
	file_proto_cloudboard_jobauth_jobauth_proto_rawDescData []byte
)

func file_proto_cloudboard_jobauth_jobauth_proto_rawDescGZIP() []byte {
	file_proto_cloudboard_jobauth_jobauth_proto_rawDescOnce.Do(func() {
		file_proto_cloudboard_jobauth_jobauth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_cloudboard_jobauth_jobauth_proto_rawDesc), len(file_proto_cloudboard_jobauth_jobauth_proto_rawDesc)))
	})
	return file_proto_cloudboard_jobauth_jobauth_proto_rawDescData
}

var file_proto_cloudboard_jobauth_jobauth_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_cloudboard_jobauth_jobauth_proto_goTypes = []any{
	(*GenerateTokenRequest)(nil),  // 0: cloudboard.jobauth.GenerateTokenRequest
	(*GenerateTokenResponse)(nil), // 1: cloudboard.jobauth.GenerateTokenResponse
	(*ValidateTokenRequest)(nil),  // 2: cloudboard.jobauth.ValidateTokenRequest
	(*ValidateTokenResponse)(nil), // 3: cloudboard.jobauth.ValidateTokenResponse
}
var file_proto_cloudboard_jobauth_jobauth_proto_depIdxs = []int32{
	0, // 0: cloudboard.jobauth.JobAuth.GenerateToken:input_type -> cloudboard.jobauth.GenerateTokenRequest
	2, // 1: cloudboard.jobauth.JobAuth.ValidateToken:input_type -> cloudboard.jobauth.ValidateTokenRequest
	1, // 2: cloudboard.jobauth.JobAuth.GenerateToken:output_type -> cloudboard.jobauth.GenerateTokenResponse
	3, // 3: cloudboard.jobauth.JobAuth.ValidateToken:output_type -> cloudboard.jobauth.ValidateTokenResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_cloudboard_jobauth_jobauth_proto_init() }
func file_proto_cloudboard_jobauth_jobauth_proto_init() {
	if File_proto_cloudboard_jobauth_jobauth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_cloudboard_jobauth_jobauth_proto_rawDesc), len(file_proto_cloudboard_jobauth_jobauth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_cloudboard_jobauth_jobauth_proto_goTypes,
		DependencyIndexes: file_proto_cloudboard_jobauth_jobauth_proto_depIdxs,
		MessageInfos:      file_proto_cloudboard_jobauth_jobauth_proto_msgTypes,
	}.Build()
	File_proto_cloudboard_jobauth_jobauth_proto = out.File
	file_proto_cloudboard_jobauth_jobauth_proto_goTypes = nil
	file_proto_cloudboard_jobauth_jobauth_proto_depIdxs = nil
}
