// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/cloudboard/cloudboard.proto

package controller

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FetchAttestationRequest is a request for a new attestation.
type FetchAttestationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchAttestationRequest) Reset() {
	*x = FetchAttestationRequest{}
	mi := &file_proto_cloudboard_cloudboard_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchAttestationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchAttestationRequest) ProtoMessage() {}

func (x *FetchAttestationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cloudboard_cloudboard_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchAttestationRequest.ProtoReflect.Descriptor instead.
func (*FetchAttestationRequest) Descriptor() ([]byte, []int) {
	return file_proto_cloudboard_cloudboard_proto_rawDescGZIP(), []int{0}
}

// FetchAttestationResponse contains the attestation bundle.
type FetchAttestationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bundle        []byte                 `protobuf:"bytes,1,opt,name=bundle,proto3" json:"bundle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchAttestationResponse) Reset() {
	*x = FetchAttestationResponse{}
	mi := &file_proto_cloudboard_cloudboard_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchAttestationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchAttestationResponse) ProtoMessage() {}

func (x *FetchAttestationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cloudboard_cloudboard_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchAttestationResponse.ProtoReflect.Descriptor instead.
func (*FetchAttestationResponse) Descriptor() ([]byte, []int) {
	return file_proto_cloudboard_cloudboard_proto_rawDescGZIP(), []int{1}
}

func (x *FetchAttestationResponse) GetBundle() []byte {
	if x != nil {
		return x.Bundle
	}
	return nil
}

// InvokeWorkloadRequest is sent by a client to invoke a workload.
type InvokeWorkloadRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Payload may include initial job metadata or request data.
	Payload       []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeWorkloadRequest) Reset() {
	*x = InvokeWorkloadRequest{}
	mi := &file_proto_cloudboard_cloudboard_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeWorkloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeWorkloadRequest) ProtoMessage() {}

func (x *InvokeWorkloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cloudboard_cloudboard_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeWorkloadRequest.ProtoReflect.Descriptor instead.
func (*InvokeWorkloadRequest) Descriptor() ([]byte, []int) {
	return file_proto_cloudboard_cloudboard_proto_rawDescGZIP(), []int{2}
}

func (x *InvokeWorkloadRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// InvokeWorkloadResponse is returned from workload execution.
type InvokeWorkloadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeWorkloadResponse) Reset() {
	*x = InvokeWorkloadResponse{}
	mi := &file_proto_cloudboard_cloudboard_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeWorkloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeWorkloadResponse) ProtoMessage() {}

func (x *InvokeWorkloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cloudboard_cloudboard_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeWorkloadResponse.ProtoReflect.Descriptor instead.
func (*InvokeWorkloadResponse) Descriptor() ([]byte, []int) {
	return file_proto_cloudboard_cloudboard_proto_rawDescGZIP(), []int{3}
}

func (x *InvokeWorkloadResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_proto_cloudboard_cloudboard_proto protoreflect.FileDescriptor

const file_proto_cloudboard_cloudboard_proto_rawDesc = "" +
	"\n" +
	"!proto/cloudboard/cloudboard.proto\x12\x15cloudboard.controller\"\x19\n" +
	"\x17FetchAttestationRequest\"2\n" +
	"\x18FetchAttestationResponse\x12\x16\n" +
	"\x06bundle\x18\x01 \x01(\fR\x06bundle\"1\n" +
	"\x15InvokeWorkloadRequest\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\"2\n" +
	"\x16InvokeWorkloadResponse\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload2\xf4\x01\n" +
	"\n" +
	"CloudBoard\x12s\n" +
	"\x10FetchAttestation\x12..cloudboard.controller.FetchAttestationRequest\x1a/.cloudboard.controller.FetchAttestationResponse\x12q\n" +
	"\x0eInvokeWorkload\x12,.cloudboard.controller.InvokeWorkloadRequest\x1a-.cloudboard.controller.InvokeWorkloadResponse(\x010\x01BFZDgithub.com/iamsourabh-in/security-pcc-go/proto/cloudboard/controllerb\x06proto3"

var (
	file_proto_cloudboard_cloudboard_proto_rawDescOnce sync.Once
	file_proto_cloudboard_cloudboard_proto_rawDescData []byte
)

func file_proto_cloudboard_cloudboard_proto_rawDescGZIP() []byte {
	file_proto_cloudboard_cloudboard_proto_rawDescOnce.Do(func() {
		file_proto_cloudboard_cloudboard_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_cloudboard_cloudboard_proto_rawDesc), len(file_proto_cloudboard_cloudboard_proto_rawDesc)))
	})
	return file_proto_cloudboard_cloudboard_proto_rawDescData
}

var file_proto_cloudboard_cloudboard_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_cloudboard_cloudboard_proto_goTypes = []any{
	(*FetchAttestationRequest)(nil),  // 0: cloudboard.controller.FetchAttestationRequest
	(*FetchAttestationResponse)(nil), // 1: cloudboard.controller.FetchAttestationResponse
	(*InvokeWorkloadRequest)(nil),    // 2: cloudboard.controller.InvokeWorkloadRequest
	(*InvokeWorkloadResponse)(nil),   // 3: cloudboard.controller.InvokeWorkloadResponse
}
var file_proto_cloudboard_cloudboard_proto_depIdxs = []int32{
	0, // 0: cloudboard.controller.CloudBoard.FetchAttestation:input_type -> cloudboard.controller.FetchAttestationRequest
	2, // 1: cloudboard.controller.CloudBoard.InvokeWorkload:input_type -> cloudboard.controller.InvokeWorkloadRequest
	1, // 2: cloudboard.controller.CloudBoard.FetchAttestation:output_type -> cloudboard.controller.FetchAttestationResponse
	3, // 3: cloudboard.controller.CloudBoard.InvokeWorkload:output_type -> cloudboard.controller.InvokeWorkloadResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_cloudboard_cloudboard_proto_init() }
func file_proto_cloudboard_cloudboard_proto_init() {
	if File_proto_cloudboard_cloudboard_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_cloudboard_cloudboard_proto_rawDesc), len(file_proto_cloudboard_cloudboard_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_cloudboard_cloudboard_proto_goTypes,
		DependencyIndexes: file_proto_cloudboard_cloudboard_proto_depIdxs,
		MessageInfos:      file_proto_cloudboard_cloudboard_proto_msgTypes,
	}.Build()
	File_proto_cloudboard_cloudboard_proto = out.File
	file_proto_cloudboard_cloudboard_proto_goTypes = nil
	file_proto_cloudboard_cloudboard_proto_depIdxs = nil
}
