// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/cloudboard/jobhelper/jobhelper.proto

package jobhelper

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// WorkloadRequest is sent to request workload operations.
type WorkloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkloadRequest) Reset() {
	*x = WorkloadRequest{}
	mi := &file_proto_cloudboard_jobhelper_jobhelper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadRequest) ProtoMessage() {}

func (x *WorkloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cloudboard_jobhelper_jobhelper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadRequest.ProtoReflect.Descriptor instead.
func (*WorkloadRequest) Descriptor() ([]byte, []int) {
	return file_proto_cloudboard_jobhelper_jobhelper_proto_rawDescGZIP(), []int{0}
}

func (x *WorkloadRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// WorkloadResponse is sent in response to workload requests.
type WorkloadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkloadResponse) Reset() {
	*x = WorkloadResponse{}
	mi := &file_proto_cloudboard_jobhelper_jobhelper_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadResponse) ProtoMessage() {}

func (x *WorkloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cloudboard_jobhelper_jobhelper_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadResponse.ProtoReflect.Descriptor instead.
func (*WorkloadResponse) Descriptor() ([]byte, []int) {
	return file_proto_cloudboard_jobhelper_jobhelper_proto_rawDescGZIP(), []int{1}
}

func (x *WorkloadResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// TeardownRequest indicates teardown operation.
type TeardownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TeardownRequest) Reset() {
	*x = TeardownRequest{}
	mi := &file_proto_cloudboard_jobhelper_jobhelper_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeardownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeardownRequest) ProtoMessage() {}

func (x *TeardownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cloudboard_jobhelper_jobhelper_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeardownRequest.ProtoReflect.Descriptor instead.
func (*TeardownRequest) Descriptor() ([]byte, []int) {
	return file_proto_cloudboard_jobhelper_jobhelper_proto_rawDescGZIP(), []int{2}
}

func (x *TeardownRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// EmptyResponse is a placeholder for empty responses.
type EmptyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyResponse) Reset() {
	*x = EmptyResponse{}
	mi := &file_proto_cloudboard_jobhelper_jobhelper_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyResponse) ProtoMessage() {}

func (x *EmptyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cloudboard_jobhelper_jobhelper_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyResponse.ProtoReflect.Descriptor instead.
func (*EmptyResponse) Descriptor() ([]byte, []int) {
	return file_proto_cloudboard_jobhelper_jobhelper_proto_rawDescGZIP(), []int{3}
}

var File_proto_cloudboard_jobhelper_jobhelper_proto protoreflect.FileDescriptor

const file_proto_cloudboard_jobhelper_jobhelper_proto_rawDesc = "" +
	"\n" +
	"*proto/cloudboard/jobhelper/jobhelper.proto\x12\x14cloudboard.jobhelper\"+\n" +
	"\x0fWorkloadRequest\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\",\n" +
	"\x10WorkloadResponse\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\"+\n" +
	"\x0fTeardownRequest\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\"\x0f\n" +
	"\rEmptyResponse2\xc8\x01\n" +
	"\tJobHelper\x12c\n" +
	"\x0eInvokeWorkload\x12%.cloudboard.jobhelper.WorkloadRequest\x1a&.cloudboard.jobhelper.WorkloadResponse(\x010\x01\x12V\n" +
	"\bTeardown\x12%.cloudboard.jobhelper.TeardownRequest\x1a#.cloudboard.jobhelper.EmptyResponseBEZCgithub.com/iamsourabh-in/security-pcc-go/proto/cloudboard/jobhelperb\x06proto3"

var (
	file_proto_cloudboard_jobhelper_jobhelper_proto_rawDescOnce sync.Once
	file_proto_cloudboard_jobhelper_jobhelper_proto_rawDescData []byte
)

func file_proto_cloudboard_jobhelper_jobhelper_proto_rawDescGZIP() []byte {
	file_proto_cloudboard_jobhelper_jobhelper_proto_rawDescOnce.Do(func() {
		file_proto_cloudboard_jobhelper_jobhelper_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_cloudboard_jobhelper_jobhelper_proto_rawDesc), len(file_proto_cloudboard_jobhelper_jobhelper_proto_rawDesc)))
	})
	return file_proto_cloudboard_jobhelper_jobhelper_proto_rawDescData
}

var file_proto_cloudboard_jobhelper_jobhelper_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_cloudboard_jobhelper_jobhelper_proto_goTypes = []any{
	(*WorkloadRequest)(nil),  // 0: cloudboard.jobhelper.WorkloadRequest
	(*WorkloadResponse)(nil), // 1: cloudboard.jobhelper.WorkloadResponse
	(*TeardownRequest)(nil),  // 2: cloudboard.jobhelper.TeardownRequest
	(*EmptyResponse)(nil),    // 3: cloudboard.jobhelper.EmptyResponse
}
var file_proto_cloudboard_jobhelper_jobhelper_proto_depIdxs = []int32{
	0, // 0: cloudboard.jobhelper.JobHelper.InvokeWorkload:input_type -> cloudboard.jobhelper.WorkloadRequest
	2, // 1: cloudboard.jobhelper.JobHelper.Teardown:input_type -> cloudboard.jobhelper.TeardownRequest
	1, // 2: cloudboard.jobhelper.JobHelper.InvokeWorkload:output_type -> cloudboard.jobhelper.WorkloadResponse
	3, // 3: cloudboard.jobhelper.JobHelper.Teardown:output_type -> cloudboard.jobhelper.EmptyResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_cloudboard_jobhelper_jobhelper_proto_init() }
func file_proto_cloudboard_jobhelper_jobhelper_proto_init() {
	if File_proto_cloudboard_jobhelper_jobhelper_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_cloudboard_jobhelper_jobhelper_proto_rawDesc), len(file_proto_cloudboard_jobhelper_jobhelper_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_cloudboard_jobhelper_jobhelper_proto_goTypes,
		DependencyIndexes: file_proto_cloudboard_jobhelper_jobhelper_proto_depIdxs,
		MessageInfos:      file_proto_cloudboard_jobhelper_jobhelper_proto_msgTypes,
	}.Build()
	File_proto_cloudboard_jobhelper_jobhelper_proto = out.File
	file_proto_cloudboard_jobhelper_jobhelper_proto_goTypes = nil
	file_proto_cloudboard_jobhelper_jobhelper_proto_depIdxs = nil
}
