// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/cloudboard/attestation.proto

package attestation

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AttestRequest is the request message for Attest.
type AttestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttestRequest) Reset() {
	*x = AttestRequest{}
	mi := &file_proto_cloudboard_attestation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttestRequest) ProtoMessage() {}

func (x *AttestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cloudboard_attestation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttestRequest.ProtoReflect.Descriptor instead.
func (*AttestRequest) Descriptor() ([]byte, []int) {
	return file_proto_cloudboard_attestation_proto_rawDescGZIP(), []int{0}
}

// AttestResponse is the response message for Attest.
type AttestResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The serialized attestation bundle bytes.
	Bundle        []byte `protobuf:"bytes,1,opt,name=bundle,proto3" json:"bundle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttestResponse) Reset() {
	*x = AttestResponse{}
	mi := &file_proto_cloudboard_attestation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttestResponse) ProtoMessage() {}

func (x *AttestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cloudboard_attestation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttestResponse.ProtoReflect.Descriptor instead.
func (*AttestResponse) Descriptor() ([]byte, []int) {
	return file_proto_cloudboard_attestation_proto_rawDescGZIP(), []int{1}
}

func (x *AttestResponse) GetBundle() []byte {
	if x != nil {
		return x.Bundle
	}
	return nil
}

var File_proto_cloudboard_attestation_proto protoreflect.FileDescriptor

const file_proto_cloudboard_attestation_proto_rawDesc = "" +
	"\n" +
	"\"proto/cloudboard/attestation.proto\x12\x16cloudboard.attestation\"\x0f\n" +
	"\rAttestRequest\"(\n" +
	"\x0eAttestResponse\x12\x16\n" +
	"\x06bundle\x18\x01 \x01(\fR\x06bundle2f\n" +
	"\vAttestation\x12W\n" +
	"\x06Attest\x12%.cloudboard.attestation.AttestRequest\x1a&.cloudboard.attestation.AttestResponseB?Z=github.com/apple/security-pcc-go/proto/cloudboard/attestationb\x06proto3"

var (
	file_proto_cloudboard_attestation_proto_rawDescOnce sync.Once
	file_proto_cloudboard_attestation_proto_rawDescData []byte
)

func file_proto_cloudboard_attestation_proto_rawDescGZIP() []byte {
	file_proto_cloudboard_attestation_proto_rawDescOnce.Do(func() {
		file_proto_cloudboard_attestation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_cloudboard_attestation_proto_rawDesc), len(file_proto_cloudboard_attestation_proto_rawDesc)))
	})
	return file_proto_cloudboard_attestation_proto_rawDescData
}

var file_proto_cloudboard_attestation_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_cloudboard_attestation_proto_goTypes = []any{
	(*AttestRequest)(nil),  // 0: cloudboard.attestation.AttestRequest
	(*AttestResponse)(nil), // 1: cloudboard.attestation.AttestResponse
}
var file_proto_cloudboard_attestation_proto_depIdxs = []int32{
	0, // 0: cloudboard.attestation.Attestation.Attest:input_type -> cloudboard.attestation.AttestRequest
	1, // 1: cloudboard.attestation.Attestation.Attest:output_type -> cloudboard.attestation.AttestResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_cloudboard_attestation_proto_init() }
func file_proto_cloudboard_attestation_proto_init() {
	if File_proto_cloudboard_attestation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_cloudboard_attestation_proto_rawDesc), len(file_proto_cloudboard_attestation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_cloudboard_attestation_proto_goTypes,
		DependencyIndexes: file_proto_cloudboard_attestation_proto_depIdxs,
		MessageInfos:      file_proto_cloudboard_attestation_proto_msgTypes,
	}.Build()
	File_proto_cloudboard_attestation_proto = out.File
	file_proto_cloudboard_attestation_proto_goTypes = nil
	file_proto_cloudboard_attestation_proto_depIdxs = nil
}
