// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: proto/cloudboard/attestation/attestation.proto

package attestation

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Attestation_Attest_FullMethodName = "/cloudboard.attestation.Attestation/Attest"
)

// AttestationClient is the client API for Attestation service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Attestation provides node attestation services.
type AttestationClient interface {
	// Attest performs a device attestation and returns an attestation bundle.
	Attest(ctx context.Context, in *AttestRequest, opts ...grpc.CallOption) (*AttestResponse, error)
}

type attestationClient struct {
	cc grpc.ClientConnInterface
}

func NewAttestationClient(cc grpc.ClientConnInterface) AttestationClient {
	return &attestationClient{cc}
}

func (c *attestationClient) Attest(ctx context.Context, in *AttestRequest, opts ...grpc.CallOption) (*AttestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AttestResponse)
	err := c.cc.Invoke(ctx, Attestation_Attest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AttestationServer is the server API for Attestation service.
// All implementations must embed UnimplementedAttestationServer
// for forward compatibility.
//
// Attestation provides node attestation services.
type AttestationServer interface {
	// Attest performs a device attestation and returns an attestation bundle.
	Attest(context.Context, *AttestRequest) (*AttestResponse, error)
	mustEmbedUnimplementedAttestationServer()
}

// UnimplementedAttestationServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAttestationServer struct{}

func (UnimplementedAttestationServer) Attest(context.Context, *AttestRequest) (*AttestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Attest not implemented")
}
func (UnimplementedAttestationServer) mustEmbedUnimplementedAttestationServer() {}
func (UnimplementedAttestationServer) testEmbeddedByValue()                     {}

// UnsafeAttestationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AttestationServer will
// result in compilation errors.
type UnsafeAttestationServer interface {
	mustEmbedUnimplementedAttestationServer()
}

func RegisterAttestationServer(s grpc.ServiceRegistrar, srv AttestationServer) {
	// If the following call pancis, it indicates UnimplementedAttestationServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Attestation_ServiceDesc, srv)
}

func _Attestation_Attest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttestationServer).Attest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Attestation_Attest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttestationServer).Attest(ctx, req.(*AttestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Attestation_ServiceDesc is the grpc.ServiceDesc for Attestation service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Attestation_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cloudboard.attestation.Attestation",
	HandlerType: (*AttestationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Attest",
			Handler:    _Attestation_Attest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/cloudboard/attestation/attestation.proto",
}
